name: CI/CD

on:
  push:
    branches:
      - main
      - develop # Add this if you use a 'develop' branch for feature integration
  pull_request:
    branches:
      - main
      - develop # Add this if you use a 'develop' branch for feature integration

jobs:
  build-and-test:
    runs-on: ubuntu-latest # You can also use windows-latest or macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify your Python version, e.g., '3.8', '3.9', '3.10', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Only install pytest here if it's not already in your requirements.txt
        pip install pytest

    - name: Run Pytest tests
      run: |
        # If you have specific test files or a test discovery setup, adjust this
        pytest